version: 0.0 
os: linux 
files: 
  - source: site 
    destination: /var/www/my-application/site/
hooks:
  ApplicationStart:
    - location: .aws/stopApplication.sh
    - location: .aws/startApplication.sh 
