AWSTemplateFormatVersion: 2010-09-09
Description: My First template cloudformation
Parameters:
  MyPublicIP:
    Type: String
    Description: My own public IP.
    Default: 86.236.61.199/32
  MyKeyName:
    Type: String
    Description: My own key name.
    Default: pcourt-01
  Env:
    Type: String
    Description: ...
    Default: test
  DbUser:
    Type: String
    Description: ...
    Default: admin
  DbPassword:
    Type: String
    Description: ...
    Default: Coucou123!
  BranchRepo:
    Type: String
    Description: ...
    Default: master
  GitRepo:
    Type: String
    Description: ...
    Default: ChoixRestoHtmlCss
  GithubUser:
    Type: String
    Description: ...
    Default: Piercuta
Resources:
  RDSInstanceSG:
    Type: 'AWS::RDS::DBSecurityGroup'
    Properties:
      GroupDescription: Enable database access to Beanstalk application
      DBSecurityGroupIngress:
        - EC2SecurityGroupName: !Ref EC2SG
        - CIDRIP: !Ref MyPublicIP
      Tags:
        - Key: Name
          Value: mysql-test-instance-sg
  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      MasterUserPassword: !Ref DbPassword
      DBInstanceClass: db.t2.micro
      DBSecurityGroups:
        - !Ref RDSInstanceSG
      MasterUsername: !Ref DbUser
      DBInstanceIdentifier: !Join 
        - '-'
        - - mysql
          - cicd
          - !Ref Env
      DBName: MySqlCF
      MultiAZ: false
      Engine: mysql
      AllocatedStorage: 5
      Tags:
        - Key: tag1
          Value: value1
        - Key: tag2
          Value: value2
  EC2SG:
    Properties:
      GroupDescription: SecurityGroup for RDS environment.
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: '22'
          ToPort: '22'
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          FromPort: '5000'
          ToPort: '5000'
          IpProtocol: tcp
    Type: 'AWS::EC2::SecurityGroup'
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-063d4ab14480ac177
      IamInstanceProfile: !Ref EC2InstanceProfile
      KeyName: !Ref MyKeyName
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref EC2SG
      UserData:
          Fn::Base64: !Sub |
             #!/bin/bash -xe
             cd /var/
             mkdir www
             cd www/
             mkdir choixresto
             sudo rpm -Uvh 'https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm'
             sudo yum install dotnet-sdk-3.1 -y
             yum install -y ruby
             cd /home/ec2-user/
             wget 'https://aws-codedeploy-eu-west-1.s3.eu-west-1.amazonaws.com/latest/install'
             chmod +x ./install
             sudo ./install auto
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - instance
              - !Ref Env
        - Key: app
          Value: choixresto
        - Key: env
          Value: !Ref Env
  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref EC2InstanceRole
  EC2InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM'
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      Path: /
  DeployApplication:
    Type: 'AWS::CodeDeploy::Application'
    Properties:
      ApplicationName: choixresto-app
      ComputePlatform: Server
  DeploymentGroup:
    Type: 'AWS::CodeDeploy::DeploymentGroup'
    Properties:
      ApplicationName: !Ref DeployApplication
      Ec2TagFilters:
        - Key: app
          Type: KEY_AND_VALUE
          Value: choixresto
        - Key: env
          Type: KEY_AND_VALUE
          Value: !Ref Env
      ServiceRoleArn: !GetAtt 
        - CodeDeployDGRole
        - Arn
  CodeDeployDGRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      Path: /
  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      Path: /
  CodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Join 
        - '-'
        - - CODEBUILD
          - !Ref Env
      Description: A description about my project
      LogsConfig:
        CloudWatchLogs: 
          Status: DISABLED 
      ServiceRole: !GetAtt 
        - CodeBuildRole
        - Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:3.0'
        EnvironmentVariables:
          - Name: CS
            Type: PLAINTEXT
            Value: !Join 
              - ''
              - - server=
                - !GetAtt 
                  - RDSInstance
                  - Endpoint.Address
                - ;user id=
                - !Ref DbUser
                - ;password=
                - !Ref DbPassword
                - ;database=ChoixResto
      Source:
        Type: CODEPIPELINE
  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'
      Path: /
  ArtifactBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: 'Token for accessing github repo'
      Name:
        !Sub
          - 'github_token_${environment}'
          - { environment: !Ref Env }
      SecretString: 
        !Sub
          - '{"github_access_token_${environment}": "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"}'
          - { environment: !Ref Env }         
  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    DependsOn: Secret
    Properties:
      Name: !Join 
        - '-'
        - - CODEPIPELINE
          - !Ref Env
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      RoleArn: !GetAtt 
        - CodePipelineRole
        - Arn
      Stages:
        - Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: !Ref GithubUser
                Repo: !Ref GitRepo
                Branch: !Ref BranchRepo
                OAuthToken: 
                    !Sub
                      - '{{resolve:secretsmanager:github_token_${environment}:SecretString:github_access_token_${environment}}}'
                      - { environment: !Ref Env }
                PollForSourceChanges: false
              RunOrder: 1
          Name: SOURCE
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref CodeBuild
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployAction
              InputArtifacts:
                - Name: BuildArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CodeDeploy
              Configuration:
                ApplicationName: !Ref DeployApplication
                DeploymentGroupName: !Ref DeploymentGroup
              RunOrder: 1
Outputs: {}
